### ISSUE TITLE
A working app

### ISSUE THREAD

**Issue by rafcontreras** [vaxxnz/nzcp-js#39]
Hi, this is not an issue.

Just wanted to share here my implementation of a COVID pass scanner using your library:

Check it out at [https://vaxxed.as](https://vaxxed.as)

You can try some example QR codes:
[Valid Pass](https://github.com/minhealthnz/nzcovidpass-spec/blob/main/spec/examples/valid/nzcp.png)
[Expired Pass](https://github.com/minhealthnz/nzcovidpass-spec/blob/main/spec/examples/invalid/nzcp-expired-payload.png)
[Revoked Pass](https://github.com/minhealthnz/nzcovidpass-spec/blob/main/spec/examples/invalid/nzcp-revoked-public-key.png)

It works offline if you've visited the site at least once, so if you don't have internet connection, you still can scan these codes. 

You can add it to your homescreen and it will work like a native app.

It uses ServiceWorkers to cache the app and use it offline.
The QR code identification and verification is done using WebWorkers so it will be very fast

**Comment by noway** [comment]
That's awesome, great job! Just wondering, are you planning to open source it?

**Comment by noway** [comment]
Feel free to join our Discord server and announce it btw! I wanted to shout you out, but it looks like you're not there yet :-) 

https://discord.gg/nkbnqhR8A8

**Comment by rafcontreras** [comment]
@noway I've made public my repo https://github.com/rafcontreras/vaxxed-as

**Comment by noway** [comment]
Amazing to have vaxxed.as under vaxxnz umbrella. Closing the issue.
