### ISSUE TITLE
Legit pass fails the test

### ISSUE THREAD

**Issue by noway** [vaxxnz/nzcp-js#43]
We're getting reports that legit passes fail the tests. Can we get our hands on one?

**Comment by noway** [comment]
```{
  "iss": "did:web:nzcp.identity.health.nz",
  "nbf": 1651665600,
  "exp": 1636023600,
  "vc": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://health.govt.nz/credentials/cpnz"
    ],
    "version": "1.0.0",
    "type": [
      "VerifiableCredential",
      "PublicCovidPass"
    ],
    "credentialSubject": {
      "givenName": "..",
      "familyName": "..",
      "dob": "yyyy-mm-dd"
    }
  }
}
```
That is how a legit pass will look

**Comment by wseagar** [comment]
I think the issue is reported from Raf's site https://vaxxed.as which is still pointing to the test issuer, all he needs to-do it change it to using the real issuer and our main interface. (I think)

**Comment by rafcontreras** [comment]
This can be closed, it was the wrong issuer.

**Comment by zerkms** [comment]
The one I just issued at `mycovidrecord` fails with 

```json
{
  "success": false,
  "credentialSubject": null,
  "violates": {
    "message": "notFound",
    "link": "https://nzcp.covid19.health.nz/#ref:DID-CORE",
    "section": "DID-CORE.1"
  }
}
```

**Comment by noway** [comment]
vaxxed.as uses hard-coded DID document at the moment. 
For this to be resolved we're waiting for MoH to fix the CORS issue. They are on it.
