### ISSUE TITLE
Verification of JS Docs for Exposed Methods and Types

### ISSUE THREAD

**Issue by olafwrieden** [vaxxnz/nzcp-js#44]
I pushed a non-breaking change that adds basic JS Docs to the two verification methods we expose via the library.

**Requests for help:**
- [ ] Could someone please verify that the JS Docs on the functions show up correctly when the library is being implemented.
- [ ] Help improve the JS Docs for the library if you see anything missing / incorrect.
- [ ] Take a look at whether it is possible to use JS Docs to document the `VerificationResult` return structure better such that the implementer has better type context as to what the `VerificationResult` fields mean and its possible values (ie. add JS Docs to the `VerificationResult` type).

Thanks

**Comment by noway** [comment]
We had to rewrite the function for which the JS docs were written after we realised that we need the offline mode. So this issue is no longer relevant.
