### ISSUE TITLE
Return cwtClaims Credential is returning null in a violation when it can be determined 

### ISSUE THREAD

**Issue by SimonCollings** [vaxxnz/nzcp-js#50]
## Expected Behavior
If there is a failure based on exp or iss (possibly others make sense as well) then the cwtClaims Credential  should contain the information it can determine.

## Actual Behavior
If there is a failure based on exp or iss (possibly others make sense as well) then the cwtClaims Credential is null, even though they have been determined.

## Steps to Reproduce the Problem

1. Verify a exp QR code
2. See null info returned for the violation

## Specifications

- Version: Node
- Platform: Node on Windows

**Comment by noway** [comment]
This is fair enough, if the signature is valid we should return credentialSubject. I'll fix it.

**Comment by noway** [comment]
Fixed in https://github.com/vaxxnz/nzcp-js/releases/tag/1.0.2

**Comment by SimonCollings** [comment]
Amazing - thank you!! Works really well!
