### ISSUE TITLE
Package Dependency is Misleading 

### ISSUE THREAD

**Issue by nitinmuk** [vaxxnz/nzcp-js#59]
## Expected Behavior
All packages which are needed at run time like cbor, should be configured under dependencies rather than devDependencies in pakcage.json. 

## Actual Behavior
dependencies is currently empty and all dependencies are listed as devDependencies in package.json currently.

## Steps to Reproduce the Problem

1. Please check package.json

## Specifications

- Version: 1.1.0
- Platform: All

**Comment by noway** [comment]
We vendor all of our dependencies. When we had it all separated, we had an issue where `Buffer` implementation that gets bundled for browser differed from the one that gets bundled for CBOR dependency. Sometimes it would be UInt8Array, sometimes something else. When we require directly, we control what goes into the resulting bundle and we can be sure that only the implementation of `Buffer` that is currently in the bundled JS file is the one to be used.

**Comment by nitinmuk** [comment]
Thanks for explanation.
